version: "2"

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/

    db:
        image: mysql:5.7
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: ostia
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - data-mysql:/var/lib/mysql

volumes:
    data-mysql:
        driver: local
